deducs:
    naics: 81
    size: s
    include_agg_deduc: False
    normalized: True
    global_always_non_neg: True

    # features_p is the probability of the feature to be different than 0
    features_p:
        deduc_x:  0.9
        deduc_y:  0.75
        deduc_16: 0.001369
        deduc_17: 0.017539
        deduc_demo: 0.95

    # Distribution is the distribution The feature given that is not zero.
    distribution:
        deduc_x:  beta
        deduc_y:  uniform
        deduc_16: uniform
        deduc_17: uniform
        deduc_demo: beta

    parameters:
        deduc_x: 
            a: 8
            b: 8
        deduc_y: 
            low: 0
            high: 1
        deduc_16: 
            low: 0
            high: 1
        deduc_17:
            low: 0
            high: 1
        deduc_demo:
            a: 8
            b: 8

    global_always_non_neg: True

    # parameters for:
    # 'normal': 'mean', 'std'
    # 'beta':  'a', 'b'
    # 'uniform': 'low', 'high'
    # 'binomial': 'n', 'p'
    
    #@TODO: include non-negative case

    