naics: 81
size: s
gen_sample_size : 1000
include_agg_deduc: False

#deduc_prob_usage:
features_p:
    net_income: 1
    effect_tax_rate: 1
    agg_deduc: 1
    
distribution:
    net_income: normal
    effect_tax_rate: normal
    agg_deduc: beta 

parameters:
    net_income:
        mean: 0.67
        std:  0.05
    effect_tax_rate:
        mean: 0.15
        std:  0.1
    agg_deduc:
        a: 2
        b: 6


# parameters for:
# 'normal': 'mean', 'std'
# 'beta':  'a', 'b'
# 'uniform': 'low', 'high'
# 'binomial': 'n', 'p'

    