efftax_aggdeduc_netinc:
    naics: 81
    size: s
    include_agg_deduc: False
    normalized: True

    features_p:
        effect_tax_rate: 1
        agg_deduc: 1
        net_income: 1

    distribution:
        effect_tax_rate: normal
        agg_deduc: beta 
        net_income: normal

    parameters:
        effect_tax_rate:
            mean: 0.15
            std:  0.1
        agg_deduc:
            a: 2
            b: 6
        net_income:
            mean: 0.67
            std:  0.05
    global_always_non_neg: False
    always_non_neg:
        net_income: False
        effect_tax_rate: True
        agg_deduc: True


    # parameters for:
    # 'normal': 'mean', 'std'
    # 'beta':  'a', 'b'
    # 'uniform': 'low', 'high'
    # 'binomial': 'n', 'p'

    